### ISSUE TITLE
Cache the GraalVM tarball and if possible the native image binary

### ISSUE THREAD

**Issue by gurukulkarni** [rinx/setup-graalvm-ce#1]
For reference see here : https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows

**Comment by rinx** [comment]
@gurukulkarni Hi. Thanks for your request. :smile:
However, unfortunately i cannot improve this GitHub Action along with your request because the GitHub Action's cache system is just for "repository-scoped" cache, so the cache cannot be refer from other repositories.
If you want to cache GraalVM tarball, you can achieve it by writing the settings below into your workflow yaml.

```yaml
env:
  GRAALVM_VERSION: "20.0.0"
  JAVA_VERSION: "java11"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache GraalVM tarball
      id: cache-graalvm-tarball
      uses: actions/cache@v1
      with:
        path: graalvm
        key: ${{ runner.os }}-graalvm-${{ env.GRAALVM_VERSION }}-${{ env.JAVA_VERSION }}
    - name: Setup GraalVM
      if: steps.cache-graalvm-tarball.outputs.cache-hit != 'true'
      uses: rinx/setup-graalvm-ce@v0.0.1
      with:
        graalvm-version: ${{ env.GRAALVM_VERSION }}
        java-version: ${{ env.JAVA_VERSION }}
```

I didn't test it but it may work if you fix a little.

Thanks.
